### ISSUE TITLE
Use namedtuple of elements of parts_list

### ISSUE THREAD

**Issue by jamesscottbrown** [BiocomputeLab/paraSBOLv#30]
Rather than having the `parts_list` argument to functions being a `list`, I think it would be clearer to use a [`namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple).

This can be defined with:

```python
from collections import namedtuple

Part = namedtuple('part', ['glyph_type', 'orientation',  'user_parameters', 'style_parameters'])
```

Then a tuple can be created with:
```python
part = Part('CDS', 'forward' , {'arrowbody_height':15}, None)

# or, from an array:

part_array = ['CDS', 'forward' , {'arrowbody_height':15}, None]
part = Part(*part_array)
```

This namedtuple has a more explicit string representation, and components can be accessed by name as well as by index:

```python
>>> print(part)
part(glyph_type='CDS', orientation='forward', user_parameters={'arrowbody_height': 15}, style_parameters=None)
>>> part.orientation
'forward'
>>> part[1]
'forward'
```

Similarly, the `bounds` list-of-lists coule be replaced by:
```python
Point = namedtuple('point', ['x', 'y'])
Bounds = namedtuple('bounds', ['lower_left', 'top_right'])
```

```python
>>> Bounds(Point(1, 2), Point(3, 4))
bounds(lower_left=point(x=1, y=2), top_right=point(x=3, y=4))
```

**Comment by cclark1e** [comment]
paraSBOLv is handling named tuples fine without any changes (from what I can tell) so all that needs to be done is changing the examples -- I'm happy to do this.

just to be sure, do you know of any error-raising cases where code written to handle lists might fail to handle named tuples?

**Comment by chofski** [comment]
This all sounds fine to me. I assume this is a mature part of the Python standard library? @cclark1e if you are able to update the examples that would be great. If you can link this issue then I'll close once the PR is merged.

**Comment by cclark1e** [comment]
I'll PR now -- I made a branch with the updated examples a few days ago
