### ISSUE TITLE
Tutorial and user guide

### ISSUE THREAD

**Issue by chofski** [BiocomputeLab/paraSBOLv#34]
It would be useful to have a tutorial on how to use the core functions of the library and also a description of how to create new pSVG files.

**Comment by chofski** [comment]
These should be extended to each of the core tools we develop (e.g. sbolv-cli)

**Comment by cclark1e** [comment]
On Friday I wrote a 'getting started' module on the basics that should automatically be incorporated into the docs - maybe a pSVG file creation section could be appended to that?

**Comment by chofski** [comment]
I'll take a look. Where is it?

**Comment by cclark1e** [comment]
[getting_started.py in the main parasbolv directory.](https://github.com/BiocomputeLab/paraSBOLv/blob/master/parasbolv/getting_started.py) I made it a ''module'' so that it gets automatically included at the front of the documentation (it's also currently on the docs) but it can be moved if needed.

**Comment by chofski** [comment]
I'll move it to a separate markdown document. Prefer to keep code, code.

**Comment by chofski** [comment]
I've cleaned up the tutorial @cclark1e. I think it is nearly there. Is there anything you can see that is missing. I was thinking it might be good to also include the basic drawing of interactions, without a construct as this is core basic functionality you'd need to know if building a tool. Developers are unlikely to use the Construct object but instead write there own customised for their needs.

**Comment by chofski** [comment]
P.S. all these are in the `tutorials` folder.

**Comment by chofski** [comment]
These have been updated and are ready for an initial release.
